apps/book_reviews/urls.py
from django.conf.urls import url
from . import views
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^home$', views.home_page, name="homepage"),
    url(r'^login$', views.login, name="login"),
    url(r'^register$', views.register, name="register"),
    url(r'^add_book$', views.add_book, name="add_book"),
    url(r'^create_book$', views.create_book, name="create_book"),
    url(r'^book_page/(?P<id>\d+)', views.book_page, name="book_page"),
    url(r'^create_review/(?P<id>\d+)$', views.create_review, name='create_review'),
    url(r'logout', views.logout, name="logout"),
    url(r'^user_page/(?P<id>\d+)$', views.user_page, name="user_page"),
    url(r'delete_review/(?P<id>\d+)/book/(?P<book_id>\d+)$', views.delete_review, name="delete_review"),

]

belt_reviewer/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.book_reviews.urls', namespace="book_reviews"))
]

apps/book_reviews/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
import re, bcrypt


EMAIL_REGEX = re.compile(r"^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$")
NAME_REGEX = re.compile(r'^[a-zA-Z]')
PASS_REGEX = re.compile(r'^\d.*[A-Z]|[A-Z].*\d')



class UserManager(models.Manager):
    def register(self, user_dict):
        error_list = []
        properly_validated = True

        if len(user_dict['first_name']) < 2 or len(user_dict['last_name']) < 2:
            error_list.append('First or Last name too short')
            properly_validated = False

        if len(user_dict['password']) < 8:
            error_list.append('Password is too short')
            properly_validated = False

        if user_dict['password'] != user_dict['confirm_password']:
            error_list.append('Passwords do not match')
            properly_validated = False

        if not EMAIL_REGEX.match(user_dict['email']):
            error_list.append('First or Last name too short')
            properly_validated = False
            
        if not NAME_REGEX.match(user_dict['first_name']):
            error_list.append('Name can only have letters')
            properly_validated = False

        if not NAME_REGEX.match(user_dict['last_name']):
            error_list.append('Name can only have letters')
            properly_validated = False

        # if not PASS_REGEX.match(user_dict['password']):
        #     error_list.append('Password requires upper case and special character')
        #     properly_validated = False
        
        if properly_validated == True:
            salt = bcrypt.gensalt()
            hashed_pw = bcrypt.hashpw(str(user_dict['password']), salt)
            try:
                User.objects.create(first_name=user_dict['first_name'], last_name=user_dict['last_name'], email=user_dict['email'], password=hashed_pw, salt=salt)
                return (properly_validated)
            except:
                properly_validated = False
                error_list.append('Email is already registered')
                return(properly_validated, error_list)
        else:
            return(properly_validated, error_list)
    
    
    
    
    def login(request, user_dict):
        error_list = []
        properly_logged = True
        try:
            user = User.objects.get(email=user_dict['email'])
        except:
            properly_logged = False
            error_list.append("Email does not exist, please register")
            return(properly_logged, error_list)
        
        if bcrypt.hashpw(str(user_dict['password']), str(user.salt)) != user.password:
            properly_logged = False
            error_list.append("Password invalid")
            return (properly_logged, error_list)

        else:
            return (properly_logged, error_list) 













class User(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.CharField(unique=True, max_length=100)
    password = models.CharField(max_length=100)
    salt = models.CharField(max_length=100, default="$2b$12$pTnZS9g9dWx1ZveqSkHL5e")
    objects = UserManager()

class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    
class Review(models.Model):
    review = models.CharField(max_length=100)
    rating = models.IntegerField()
    book = models.ForeignKey(Book, related_name='reviews')
    user = models.ForeignKey(User, related_name="reviews")
    created_at= models.DateTimeField(auto_now_add=True) 
    updated_at= models.DateTimeField(auto_now=True) 
    

apps/book_reviews/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, reverse
from .models import *
from django.contrib import messages
from django.db.models import Count

def index(request):
    return render(request, "book_reviews/index.html")


def home_page(request):
    context = {
        'books': Book.objects.all(),
        'reviews': Review.objects.all().order_by("-created_at")[:3],
        'user': User.objects.all()
    }
    
    return render(request,'book_reviews/home.html', context)


def book_page(request,id):
    context = {
        'book' : Book.objects.get(id=id),
        'reviews': Review.objects.filter(book_id=id).order_by('-created_at'),
        'user': User.objects.all() 
    }

    return render(request, 'book_reviews/book.html', context)





def add_book(request):
    context={
        'unique_authors': Book.objects.values('author').distinct()
    }



    return render(request, "book_reviews/add_book.html", context)

def register(request):
    print 'register works'
    if request.method == 'POST':
        user_dict = {
            'first_name': request.POST['first_name'],
            'last_name': request.POST['last_name'],
            'email': request.POST['email'],
            'password': request.POST['password'],
            'confirm_password': request.POST['confirm_password']            
            }
        register_result = User.objects.register(user_dict)

        if register_result == True:
            request.session['first_name'] = request.POST['first_name']
            request.session['email']  = request.POST['email'] 
            return redirect('book_reviews:homepage')
        
        elif register_result[0] == False:
            for message in register_result[1]:
                messages.add_message(request, messages.ERROR, message)
        
    return redirect('book_reviews:index')

def logout(request):
    for key in request.session.keys():
        del request.session[key]

    return redirect('book_reviews:index')
    

def login(request):
    if request.method == 'POST':
        user_dict = {
            'email': request.POST['email'],
            'password': request.POST['password']
        }
        login_result = User.objects.login(user_dict)
        

        if login_result[0] == True:
            user = User.objects.get(email=user_dict['email'])
            request.session['email']=user.email
            request.session['first_name'] = user.first_name
            print request.session['first_name']
            return redirect('book_reviews:homepage')
        if login_result[0] == False:
            for message in login_result[1]:
                messages.add_message(request, messages.ERROR, message)
            
    return redirect('book_reviews:index')

def create_book(request):
    if request.method == "POST":
        book = None
        try:
            book = Book.objects.get(title=request.POST['title'])
            #redirect to route with book and reviews
        except:
            book = Book.objects.create(title=request.POST['title'], author=request.POST['author'])
            
        rating = request.POST['stars']
        user= User.objects.get(email=request.session['email'])

        review = Review.objects.create(review=request.POST['review'], rating=int(rating), book=book, user = user)

    return redirect('book_reviews:homepage')

def create_review(request, id):
    if request.method == "POST":
        user = User.objects.get(email=request.session['email'])
        book = Book.objects.get(id=id)
        print type(book)
        rating = int(request.POST['stars'])
        Review.objects.create(review=request.POST['review'], rating=rating, book=book,user=user)

    return redirect(reverse('book_reviews:book_page', kwargs={'id': id}))


def user_page(request, id):
    context = {
        'user': User.objects.filter(id=id).annotate(num_reviews=Count('reviews'))[0],
    }
    return render(request, "book_reviews/user.html",context)

def delete_review(request, id, book_id):

    instance = Review.objects.get(id=id)
    instance.delete()
    return redirect(reverse('book_reviews:book_page', kwargs={'id':book_id}))

apps/book_reviews/templates/book_reviews/add_book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'book_reviews:create_book' %}" method="POST">
        Book Title: <input type="text" name="title"><br>
        Author: <input type="text" name="author"><br>
        <select name="author">
            {% for author in unique_authors%}
                <option value="{{author.author}}">{{author.author}} </option>
            {% endfor %}
        </select><br>
        Review: <br> <textarea rows="8" cols="40" name="review"></textarea><br>
        Rating:
        <select name='stars'>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select><br>
        <input type="submit" value="Add a book and review">
        {% csrf_token %}
    </form>


    
</body>
</html>

apps/book_reviews/templates/book_reviews/book.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>{{book.title}}</h1>
    <h3>{{book.author}}</h3>
    <h4><a href="{% url 'book_reviews:homepage'%}">Home</a></h4>
    <h2>Reviews:</h2>
    {% for review in reviews %}
        <p>{{review.rating}} star out of 5</p>
        <p><a href="{% url 'book_reviews:user_page' id=review.user.id %}">{{review.user.first_name}}</a> says: {{review.review}}</p>
        {% if request.session.email == review.user.email %}
            <a href="{% url 'book_reviews:delete_review' id=review.id book_id=book.id %}">delete</a>
        {% endif %}
        <p>Posted on: {{review.created_at}}</p>
    {% endfor %}

    <h3>Review this book!</h3>
    <form action="{% url 'book_reviews:create_review' id=book.id %}" method="POST">
        <textarea rows="8" cols="40" name="review"></textarea><br>
        Rating:
        <select name='stars'>
            <option value="1">1</option>
            <option value="2">2</option>
            <option value="3">3</option>
            <option value="4">4</option>
            <option value="5">5</option>
        </select><br>
        <input type="submit" value="Review Book">
        {% csrf_token %}
    </form>





</body>
</html>

apps/book_reviews/templates/book_reviews/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Welcome {{request.session.first_name}} </h1>
    <h4><a href="{% url 'book_reviews:logout' %}">Logout</a></h4>
    <p><a href="{% url 'book_reviews:add_book'%}">Add Book and Review</a></p>
    {% for review in reviews %}
        <p><a href="{% url 'book_reviews:book_page' id=review.book.id%}">{{review.book.title}}</a></p>
        <p><a href="{% url 'book_reviews:user_page' id=review.user.id %}">{{review.user.first_name}}</a> says: {{review.review}}</p>
        <p>{{review.review}}</p>
        <p>Rating: {{review.rating}}</p>
    {% endfor %}
    <h3>Other Books with Reviews:</h3>
    {% for book in books%}
        <p><a href="{% url 'book_reviews:book_page' id=book.id%}">{{book.title}}</p>
    {% endfor %}





</body>
</html>

apps/book_reviews/templates/book_reviews/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h1>Welcome</h1>
    <h3>Register</h3>
    <form action="{% url 'book_reviews:register'%}" method="POST"><br>
        First Name: <input type="text" name="first_name"><br>
        Last Name: <input type="text" name="last_name"><br>
        Email: <input type="text" name="email"><br>
        Password: <input type="text" name="password"><br>
        Confirm Password: <input type="text" name="confirm_password"><br>
        <input type="submit" value="Register">
        {% csrf_token %}
    </form>
     {% for message in messages %}
        <p>{{message}}</p>
    {% endfor %}
    <h3>Login</h3>
    <form action="{% url 'book_reviews:login'%}" method="POST"><br>
        Email: <input type="text" name="email"><br>
        Password: <input type="text" name="password"><br>
        <input type="submit" value="Login">
        {% csrf_token %}
    </form>


</body>
</html>

apps/book_reviews/templates/book_reviews/user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h3>User: {{user.first_name}}</h3>
    <h3>Email: {{user.email}}</h3>
    <h3>Total Reviews: {{user.num_reviews}}</h3>
</body>
</html>